### ISSUE TITLE
Writing into non-existing arrays with $last, $first and *-wildcard should be skipped?

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#369]
Came up within #368 :

While reading a path with one of the following array wildcards `$last`, `$first` and `*` skips the step due to no existing basis for reading,
writing new values with these array wildcards does not and creates a new element/array with one of wildcard as part of the pathnames 

```
in:
---
a: "Faust" 
```

[copy_field](https://metafacture.org/playground/?flux=inputFile%0A%7Copen-file%0A%7Cas-records%0A%7Cdecode-yaml%0A%7Cfix%28transformationFile%29%0A%7Cencode-yaml%0A%7Cprint%0A%3B&transformation=copy_field%28%22a%22%2C%22test.%2A.test%22%29&data=---%0Aa%3A+%22Faust%22%0A---%0Aa%3A+%22R%C3%A4uber%22)

```
fix:
copy_field("a","test.*.test")
out:
---
a: "Faust"
test:
  '*':
    test: "Faust"
```

-----
[add_field](https://metafacture.org/playground/?flux=inputFile%0A%7Copen-file%0A%7Cas-records%0A%7Cdecode-yaml%0A%7Cfix%28transformationFile%29%0A%7Cencode-yaml%0A%7Cprint%0A%3B&transformation=add_field%28%22test.%24last.test%22%2C%22a%22%29&data=---%0Aa%3A+%22Faust%22%0A---%0Aa%3A+%22R%C3%A4uber%22)

```
fix:
add_field("test.$last.test","a")
out:
---
a: "Faust"
test:
  $last:
    test: "a"
```

[set_array](https://metafacture.org/playground/?flux=inputFile%0A%7Copen-file%0A%7Cas-records%0A%7Cdecode-yaml%0A%7Cfix%28transformationFile%29%0A%7Cencode-yaml%0A%7Cprint%0A%3B&transformation=set_array%28%22test.%24first.test%22%2C%22a%22%29&data=---%0Aa%3A+%22Faust%22%0A---%0Aa%3A+%22R%C3%A4uber%22)

```
fix:
set_array("test.$first.test","a")
out:
---
a: "Faust"
test:
  $first:
    test: "a"
```

In my opinion these creations should be skipped due to non existing arrays and only $append/$prepend should create pathes.
